---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  tasks:
    - name: copy WAR to tomcat
      copy:
        src: "/var/snap/jenkins/4874/workspace/mvnwebapp/target/mvnwebapp.war"
        dest: "/opt/tomcat/webapps/mvnwebapp.war"
        remote_src: yes
        
    - name: restart tomact
      systemd:
        name: tomcat
        state: restarted
        
    
